/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ShoppingProductRequest, ShoppingProductResponse } from "./model";

export type getByIdResponse200 = {
  data: ShoppingProductResponse;
  status: 200;
};

export type getByIdResponseSuccess = getByIdResponse200 & {
  headers: Headers;
};
export type getByIdResponse = getByIdResponseSuccess;

export const getGetByIdUrl = (id: number) => {
  return `/api/shopping/${id}`;
};

export const getById = async (
  id: number,
  options?: RequestInit,
): Promise<getByIdResponse> => {
  const res = await fetch(getGetByIdUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getByIdResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getByIdResponse;
};

export const getGetByIdQueryKey = (id?: number) => {
  return [`/api/shopping/${id}`] as const;
};

export const getGetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getById>>> = ({
    signal,
  }) => getById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getById>>
>;
export type GetByIdQueryError = unknown;

export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetById<
  TData = Awaited<ReturnType<typeof getById>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type updateVeritoneShoppingProductResponse200 = {
  data: ShoppingProductResponse;
  status: 200;
};

export type updateVeritoneShoppingProductResponseSuccess =
  updateVeritoneShoppingProductResponse200 & {
    headers: Headers;
  };
export type updateVeritoneShoppingProductResponse =
  updateVeritoneShoppingProductResponseSuccess;

export const getUpdateVeritoneShoppingProductUrl = (id: number) => {
  return `/api/shopping/${id}`;
};

export const updateVeritoneShoppingProduct = async (
  id: number,
  shoppingProductRequest: ShoppingProductRequest,
  options?: RequestInit,
): Promise<updateVeritoneShoppingProductResponse> => {
  const res = await fetch(getUpdateVeritoneShoppingProductUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(shoppingProductRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateVeritoneShoppingProductResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateVeritoneShoppingProductResponse;
};

export const getUpdateVeritoneShoppingProductMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>,
    TError,
    { id: number; data: ShoppingProductRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>,
  TError,
  { id: number; data: ShoppingProductRequest },
  TContext
> => {
  const mutationKey = ["updateVeritoneShoppingProduct"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>,
    { id: number; data: ShoppingProductRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateVeritoneShoppingProduct(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateVeritoneShoppingProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>
>;
export type UpdateVeritoneShoppingProductMutationBody = ShoppingProductRequest;
export type UpdateVeritoneShoppingProductMutationError = unknown;

export const useUpdateVeritoneShoppingProduct = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>,
      TError,
      { id: number; data: ShoppingProductRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateVeritoneShoppingProduct>>,
  TError,
  { id: number; data: ShoppingProductRequest },
  TContext
> => {
  return useMutation(
    getUpdateVeritoneShoppingProductMutationOptions(options),
    queryClient,
  );
};
export type deleteVeritoneShoppingProductResponse204 = {
  data: void;
  status: 204;
};

export type deleteVeritoneShoppingProductResponseSuccess =
  deleteVeritoneShoppingProductResponse204 & {
    headers: Headers;
  };
export type deleteVeritoneShoppingProductResponse =
  deleteVeritoneShoppingProductResponseSuccess;

export const getDeleteVeritoneShoppingProductUrl = (id: number) => {
  return `/api/shopping/${id}`;
};

export const deleteVeritoneShoppingProduct = async (
  id: number,
  options?: RequestInit,
): Promise<deleteVeritoneShoppingProductResponse> => {
  const res = await fetch(getDeleteVeritoneShoppingProductUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteVeritoneShoppingProductResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteVeritoneShoppingProductResponse;
};

export const getDeleteVeritoneShoppingProductMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>,
    TError,
    { id: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteVeritoneShoppingProduct"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteVeritoneShoppingProduct(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteVeritoneShoppingProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>
>;

export type DeleteVeritoneShoppingProductMutationError = unknown;

export const useDeleteVeritoneShoppingProduct = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>,
      TError,
      { id: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteVeritoneShoppingProduct>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDeleteVeritoneShoppingProductMutationOptions(options),
    queryClient,
  );
};
export type getAllVeritoneShoppingProductsResponse200 = {
  data: ShoppingProductResponse[];
  status: 200;
};

export type getAllVeritoneShoppingProductsResponseSuccess =
  getAllVeritoneShoppingProductsResponse200 & {
    headers: Headers;
  };
export type getAllVeritoneShoppingProductsResponse =
  getAllVeritoneShoppingProductsResponseSuccess;

export const getGetAllVeritoneShoppingProductsUrl = () => {
  return `/api/shopping`;
};

export const getAllVeritoneShoppingProducts = async (
  options?: RequestInit,
): Promise<getAllVeritoneShoppingProductsResponse> => {
  const res = await fetch(getGetAllVeritoneShoppingProductsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllVeritoneShoppingProductsResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAllVeritoneShoppingProductsResponse;
};

export const getGetAllVeritoneShoppingProductsQueryKey = () => {
  return [`/api/shopping`] as const;
};

export const getGetAllVeritoneShoppingProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllVeritoneShoppingProductsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>
  > = ({ signal }) =>
    getAllVeritoneShoppingProducts({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllVeritoneShoppingProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>
>;
export type GetAllVeritoneShoppingProductsQueryError = unknown;

export function useGetAllVeritoneShoppingProducts<
  TData = Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllVeritoneShoppingProducts<
  TData = Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllVeritoneShoppingProducts<
  TData = Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllVeritoneShoppingProducts<
  TData = Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllVeritoneShoppingProducts>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllVeritoneShoppingProductsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type createVeritoneShoppingProductResponse200 = {
  data: ShoppingProductResponse;
  status: 200;
};

export type createVeritoneShoppingProductResponseSuccess =
  createVeritoneShoppingProductResponse200 & {
    headers: Headers;
  };
export type createVeritoneShoppingProductResponse =
  createVeritoneShoppingProductResponseSuccess;

export const getCreateVeritoneShoppingProductUrl = () => {
  return `/api/shopping`;
};

export const createVeritoneShoppingProduct = async (
  shoppingProductRequest: ShoppingProductRequest,
  options?: RequestInit,
): Promise<createVeritoneShoppingProductResponse> => {
  const res = await fetch(getCreateVeritoneShoppingProductUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(shoppingProductRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createVeritoneShoppingProductResponse["data"] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createVeritoneShoppingProductResponse;
};

export const getCreateVeritoneShoppingProductMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createVeritoneShoppingProduct>>,
    TError,
    { data: ShoppingProductRequest },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createVeritoneShoppingProduct>>,
  TError,
  { data: ShoppingProductRequest },
  TContext
> => {
  const mutationKey = ["createVeritoneShoppingProduct"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createVeritoneShoppingProduct>>,
    { data: ShoppingProductRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createVeritoneShoppingProduct(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateVeritoneShoppingProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof createVeritoneShoppingProduct>>
>;
export type CreateVeritoneShoppingProductMutationBody = ShoppingProductRequest;
export type CreateVeritoneShoppingProductMutationError = unknown;

export const useCreateVeritoneShoppingProduct = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createVeritoneShoppingProduct>>,
      TError,
      { data: ShoppingProductRequest },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createVeritoneShoppingProduct>>,
  TError,
  { data: ShoppingProductRequest },
  TContext
> => {
  return useMutation(
    getCreateVeritoneShoppingProductMutationOptions(options),
    queryClient,
  );
};
