/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from "./shoppingProductRequest";
export * from "./shoppingProductResponse";
